# Site settings
title: Bitcamp 2016
email: hello@bitca.mp
baseurl: ""
url: "http://bitca.mp"
typeform_url: "/register"
content_home_dir: "content_blocks_html"
sponsor_logo_dir: "/img/sponsor-logos/"
speaker_photo_dir: "/img/speaker-photos/"
colorwar_judge_photo_dir: "/img/judge-photos/"
registration_status: "closed"
