# Site settings
title: Bitcamp 2016
email: hello@bitca.mp
description: > # this means to ignore newlines until "baseurl:"
  Bitcamp is a place for exploration. You will have 36 hours to delve into your
  curiosities, learn something new, and make something awesome. With world-class mentors
  and hundreds of fellow campers, you’re in for an amazing time. If you’re ready
  for an adventure, see you by the fire!
baseurl: ""
url: "http://bitca.mp"
typeform_url: "/register"
content_home_dir: "content_blocks_html"
registration_status: "open"
